project:
  type: book

lang: es
  
bibliography: capitulos/references.bib
csl: apa.csl

citation: 
  type: book

book:
  title: "Integridad ecosistémica de costas arenosas"
  subtitle: "Proyecto Conahcyt de ciencia de frontera (CF-2023-G-1497)"
  
  downloads: [pdf, epub]
  favicon: images/plecas_Página_7.png

  sidebar: 
      background: "#B5C9B8"
      logo: images/beach-7318494_1920.jpg
      search: true
    
  page-footer:
      left: |
        [Costas Arenosas](https://sw-costas-arenosas.netlify.app/).
      right: |
        Reporte preparado con <a href="https://quarto.org/">Quarto</a>.
  cover-image: images/landscape-546343_1280.jpg
  author:
    - name: Octavio Pérez-Maqueo 
      url: https://inecol.mx/
      affiliation: Ambiente y Sustentabilidad / Inecol
      affiliation-url: https://inecol.mx
    - name: Miguel Equihua 
      url: https://inecol.mx/
      affiliation: Ambiente y Sustentabilidad / Inecol
      affiliation-url: https://inecol.mx
  date: "2024/5/23"
  chapters:
    - index.qmd
    - capitulos/summary.qmd
    - capitulos/intro.qmd
    - capitulos/taller.qmd
    - capitulos/miro-costas.qmd
    - capitulos/references.qmd
css: costas.css

format:
  html:
    theme: materia
  pdf:
    papersize: letter
    prefer-html: true
    documentclass: scrreprt
    cite-method: citeproc

  epub:
    papersize: letter
    prefer-html: true
    cover-image: images/landscape-546343_1280.jpg

execute: 
  freeze: true

