project:
  type: book

lang: es
  
bibliography: capitulos/references.bib
csl: apa.csl

citation: 
  type: book

book:
  title: "Integridad ecosistémica de costas arenosas"
  subtitle: "Proyecto Conahcyt de ciencia de frontera (CF-2023-G-1497)"
  
  downloads: [pdf]
  favicon: images/plecas_Página_7.png

  sidebar: 
      background: "#B5C9B8"
      logo: images/beach-7318494_1920.jpg
      search: true
    
  page-footer:
      left: |
        [Costas Arenosas](https://sw-costas-arenosas.netlify.app/).
      right: |
        Reporte preparado con <a href="https://quarto.org/">Quarto</a>.
  cover-image: images/landscape-546343_1280.jpg
  author:
    - name: Octavio Pérez-Maqueo 
      url: https://inecol.mx/
      affiliation: Ambiente y Sustentabilidad / Inecol
      affiliation-url: https://inecol.mx
    - name: Miguel Equihua 
      url: https://inecol.mx/
      affiliation: Ambiente y Sustentabilidad / Inecol
      affiliation-url: https://inecol.mx
  date: "2024/5/23"
  chapters:
    - index.qmd
    - capitulos/summary.qmd
    - capitulos/intro.qmd
    - capitulos/taller.qmd
    - capitulos/miro-costas.qmd
    - capitulos/references.qmd
css: costas.css

format:
  html:
    theme: materia
  titlepage-pdf:
    titlepage: bg-image
    papersize: letter
    prefer-html: true
    documentclass: scrbook
    cite-method: citeproc
    citation: true
    coverpage: true
    coverpage-bg-image: "images/landscape-546343_1280.jpg"
    coverpage-title: "Estimación de la integridad ecosistémica de las costas arenosas mexicanas a través de técnicas de aprendizaje de máquina"
    coverpage-footer: "Proyecto Conahcyt de ciencia de frontera (CF-2023-G-1497)"
    coverpage-author: ["Octavio Pérez Maqueo", "Miguel Equihua Zamora"]
    coverpage-theme:
      page-html-color: "F6D5A8"
      title-fontfamily: "QTFloraline.otf"
      title-fontsize: 36
      title-align: "right"
      title-bottom: "10in"
      author-style: "plain"
      author-sep: "newline"
      author-fontfamily: "QTAtchen.otf"
      author-fontstyle: "textsc"
      author-fontsize: 18
      author-align: "right"
      author-bottom: "7in"  
      header-style: "none"
      footer-fontsize: 16
      footer-fontfamily: "QTAtchen.otf"
      footer-align: "right"
      footer-color: "white"
      footer-bottom: "3in"
      date-style: "none"
      bg-image-fading: "north"

execute: 
  freeze: true

